version: '3.8'

services:
  # PostgreSQL Database for Development
  postgres:
    image: postgres:16-alpine
    container_name: flow-postgres-dev
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-root}
      POSTGRES_DB: ${DB_NAME:-flow_db}
    ports:
      - '${DB_PORT:-5432}:5432'
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    networks:
      - flow-network-dev

  # Redis for Queue Management in Development
  redis:
    image: redis:7-alpine
    container_name: flow-redis-dev
    restart: unless-stopped
    ports:
      - '${REDIS_PORT:-6379}:6379'
    volumes:
      - redis_dev_data:/data
    networks:
      - flow-network-dev

volumes:
  postgres_dev_data:
    driver: local
  redis_dev_data:
    driver: local

networks:
  flow-network-dev:
    driver: bridge
